### PR TITLE
Update ETL executeSQL logging

### PR DESCRIPTION
**Pull request by plessbd**
Continuing my quest for better logging
This moves notification of start of executeSQL to a notice level, and moves some debugging into info for analysis later

### CODE REVIEW

**Comment by jtpalmer** [comment]
What is the reason for increasing the log level for these messages?  What's wrong with `info`?

**Comment by plessbd** [comment]
So that when running this manually, something is output instead of see something like this (not this specific one but similar)
Where you get an end notice on something but no idea what is happening now (unless you change the log level or look at the database).

Ideally I want to also be consistent on start and end notices being at the same level.

```
2020-05-27 11:57:56 [notice] aggregate end (unit: month, periods: 1, start_date: 2020-05-13 11:40:49, end_date: none, start_time: 1590594925.4813, end_time: 1590595076.2817, elapsed_time: 150.80048)
2020-05-27 12:00:31 [notice] aggregate end (unit: quarter, periods: 1, start_date: 2020-05-13 11:40:49, end_date: none, start_time: 1590595079.357, end_time: 1590595231.5896, elapsed_time: 152.23261)
```

switching from debug -> info is so that things get logged to the database for better analysis

**Comment by jtpalmer** [comment]
We can always start logging debug messages to the database.

**Comment by plessbd** [comment]
we could, this was just a small step.

**Comment by plessbd** [comment]
Agree, but at the same time not enough verbosity is also bad.  That is what we 'should' have `-q` for...

**Comment by jtpalmer** [comment]
That is absolutely not what `-q` is for. Quiet should suppress everything that isn't an error (or warning).

**Pull request merged**
