### PR TITLE
update bootstrap and gitignore to be more specific

### PR DESCRIPTION
**Pull request by plessbd**
I need to pay more attention...

This fixes a few issues introduced in previous test updates

### CODE REVIEW

**Comment by jtpalmer** [comment]
Do you know why tests were still passing while these paths were incorrect?

**Comment by plessbd** [comment]
yes :)

**Comment by plessbd** [comment]
These diffs only do things when NOT testing the jobs realm.  Since we are *currently* always testing the jobs realms these diffs do not get applied.

**Comment by jtpalmer** [comment]
Where are the instructions to test individual realms?

**Comment by plessbd** [comment]
I will work on some documentation updates when we start building this out more, but in the sort term you set an environment variable `XDMOD_REALMS` equal to a comma separated list of currently `jobs`, `storage`, and/or `cloud`

```bash
if [ -z $XDMOD_REALMS ]; then
    export XDMOD_REALMS=jobs,storage,cloud
fi
```

**Pull request merged**
