### PR TITLE
Update About tab with recent Publications and Presentations details

### PR DESCRIPTION
**Pull request by jsperhac**
## Description

Update Publications and Presentations listed in the XDMoD/Open XDMoD About tab.  Namely:
- Add Gateways20 tutorial to Presentations; include link to the hpc-toolset-tutorial repo
- Update PEARC20 tutorial in Presentations to include repo link
- Update Publications to include recent DOIs

These changes are documentation/HTML only!

## Motivation and Context

Keep our About tab up to date with recent publications and presentations

## Tests performed

Viewed in browser.

## Checklist:

- [X] The pull request description is suitable for a Changelog entry
- [X] The milestone is set correctly on the pull request
- [X] The appropriate labels have been added to the pull request

### CODE REVIEW

**Comment by jpwhite4** [comment]
Its probably worth addressing the <b> to <strong> identified by sonar cloud.

**Comment by jsperhac** [comment]
Sonar Cloud is asking to have <b> tags replaced by <strong>. The rest of the html in the About section uses bold tags as well. Should they all be changed?

**Comment by jpwhite4** [comment]
> Sonar Cloud is asking to have html "bold" `(<b>)` tags replaced by "strong" `(<strong>)` tags here. The rest of the html in the About section uses bold tags as well. Should they all be changed?

I suppose we should fix them (as long as the changes don't lead down a rabbit hole of more detected problems)..

**Comment by jsperhac** [comment]
Replaced both bold and font elements in the publications and presentations files (both are deprecated html). Shippable appears to be failing on a missing logfile.

I will replace bold and font elements of other About section files in a follow-on PR (see also #1474, which updates authors and the XMS team, while updating deprecated html in the effected pages)

**Comment by jsperhac** [comment]
Issue is fixed (next time I'll scroll up and read all the error messages...). This PR concludes the changes for html compliance in the About tab, and updates our publications and presentation pages as well.

**Review by jpwhite4 — APPROVED** [review]

**Pull request merged**
