### PR TITLE
Fixing Center Syncing w/ SSO Users

### PR DESCRIPTION
**Pull request by ryanrath**
## Description
While we were updating a Users's organization during `XDUser::postLogin` we were
not keeping `user_acl_group_by_parameters` in sync. This caused their old
organization to be shown when viewing the `Top Role` section of `My Profile`.

## Motivation and Context
Consistency is good.

## Tests performed
Manual Tests were performed
- Update an SSO User's person to 'Unknown, Unknown' and their organization to 'Unk' 
  - Make a note of their original organization if it's different than their SSO organization.
- Assign either: `Center Director` or `Center Staff` if they do not already have one of these acls.
- Login as that user ( via SSO )
- Click the 'My Profile' button
- Ensure that the 'Top Role' is displayed as expected.
  - ex. Center Staff - SUNY Buffalo

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project as found in the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by jpwhite4** [comment]
How does this change fit in with the proposed changes of #752

**Comment by ryanrath** [comment]
I plead food coma, that next PR is actually up already: #760

**Comment by ryanrath** [comment]
@jpwhite4 @smgallo This PR (https://github.com/ubccr/xdmod/pull/760) would obviate the need for the changes in this PR and do so without adding additional code.

**Comment by ryanrath** [comment]
I'm going to go ahead and close this PR since (#760) is a better way of fixing this.

**Pull request closed without merging**
