### PR TITLE
Use stronger password hashing algorithm

### PR DESCRIPTION
**Pull request by jpwhite4**
See asana issue https://app.asana.com/0/14740318781081/578673499549601

### CODE REVIEW

**Comment by jpwhite4** [comment]
Note that the "upgrade" part of the CI tests are expected to fail until such a time as the docker image is updated to 7.5.

**Comment by jpwhite4** [comment]
Note that the upgrade tests are now failing because the sql migration script is not being run.

**Comment by plessbd** [comment]
migrations should be fixed with #453

**Comment by plessbd** [comment]
see #454

**Comment by plessbd** [comment]
Composer will need to be updated now that #420 has been merged

**Pull request closed without merging**
