### PR TITLE
Change default log directory permissions

### PR DESCRIPTION
**Pull request by jtpalmer**
## Description

Changes the default permissions of the log directory to be `0770`.

## Motivation and Context

This is intended to improve security.

## Tests performed

Tested manually.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project as found in the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by jpwhite4** [comment]
https://app.asana.com/0/342819846538629/1178746552707810

**Comment by jpwhite4** [comment]
Should we also change the   
```rpm
   chmod 0664 %{_localstatedir}/log/%{name}/$file
```
in the rpm post section to 660?

**Comment by jtpalmer** [comment]
@jpwhite4 I think that makes sense. I'll change it.

**Comment by jtpalmer** [comment]
We might want to completely remove that block from the post section since it was intended for a specific upgrade when we originally changed those permissions (#355).

**Pull request merged**
