### PR TITLE
Changing name of Utilization metric to CPU Utilization

### PR DESCRIPTION
**Pull request by eiffel777**
Change the name of the Utilization metric to CPU Utilization as it is more accurate. Updated tests with the new name.

## Tests performed
Tested in docker

## Checklist:

- [x] The pull request description is suitable for a Changelog entry
- [x] The milestone is set correctly on the pull request
- [x] The appropriate labels have been added to the pull request

### CODE REVIEW

**Review by aaronweeden — CHANGES_REQUESTED** [review]
Gateways realm also needs updating.

**Comment by aaronweeden** [comment]
`configuration/etl/etl_data.d/xdb/report-template-charts.json` has some charts with names that should perhaps be changed from `Percent Utilization` to `Percent CPU Utilization`.

**Comment by eiffel777** [comment]
> Gateways realm also needs updating.

This is done.

**Review by ryanrath — APPROVED** [review]

**Review by aaronweeden — DISMISSED** [review]
I'm assuming we don't want to change the names of charts in users' existing reports in the report generator? If so, looks good.

**Review by aaronweeden — APPROVED** [review]

**Pull request merged**
