### PR TITLE
Add explicit ordering for Job Viewer analytics panel.

### PR DESCRIPTION
**Pull request by aaronweeden**
## Description

This PR makes the Job Viewer's analytics panel explicitly display the metrics in the order they are currently displayed (1. `CPU User`, 2. `Homogeneity`, 3. `CPU User Balance`, 4. `Memory Headroom`, 5. `Walltime Accuracy`) rather than displaying them in whatever order they are returned by the `rest/warehouse/search/jobs/analytics` endpoint. This will be needed for https://github.com/ubccr/xdmod-supremm/pull/256 since that PR will cause the metrics to be in a different order when they are returned by the endpoint.

## Tests performed

In a Docker container running `tools-ext-01.ccr.xdmod.org/xdmod-job_performance-10.5.0:rockylinux8-0.1`:
1. Run the following commands:
    ```
    export COMPOSER_ALLOW_SUPERUSER=1
    export XDMOD_REALMS='jobs,storage,cloud,supremm,jobefficiency'
    export XDMOD_IS_CORE=yes
    export XDMOD_INSTALL_DIR=/xdmod
    export XDMOD_TEST_MODE=upgrade
    export XDMOD_SRC_DIR=./../xdmod
    git clone https://github.com/jtpalmer/xdmod-supremm -b jobdataset-analytics-fields /xdmod-supremm
    cd /xdmod-supremm
    dnf module -y reset nodejs
    dnf module -y install nodejs:16
    git clone https://github.com/ubccr/xdmod $XDMOD_SRC_DIR
    ln -s `pwd` $XDMOD_SRC_DIR/open_xdmod/modules/supremm
    ./tests/ci/scripts/install_mongo.sh
    composer install --no-progress
    composer config -g cache-files-ttl 315360000
    composer install -d $XDMOD_SRC_DIR --no-progress
    mkdir -p ~/phpunit
    mkdir -p /tmp/screenshots
    export XDMOD_SOURCE_DIR=/xdmod
    export SHIPPABLE_BUILD_DIR=/xdmod-supremm
    pushd $XDMOD_SRC_DIR
    ~/bin/buildrpm xdmod supremm
    popd
    ./tests/integration/scripts/bootstrap.sh
    ./tests/integration/scripts/validate.sh
    ```
1. In a web browser, browse to the localhost portal.
1. Sign in as `centerdirector`.
1. Go to the Metric Explorer.
1. Select `SUPREMM` > `CPU Hours Total` > `Application`.
1. Set the date range to `2016-12-01`–`2017-01-01`.
1. Select a data point and choose `Show Raw Data`.
1. Select a job in the list.
1. Confirm the order of the analytics metrics is incorrect.
1. Copy `html/gui/js/modules/job_viewer/JobPanel.js` from this PR to `/usr/share/xdmod/html/gui/js/modules/job_viewer/JobPanel.js`.
1. Refresh the browser and confirm the order of the analytics metrics is correct and there are no errors on the JavaScript console.

## Checklist:

- [x] The pull request description is suitable for a Changelog entry
- [x] The milestone is set correctly on the pull request
- [x] The appropriate labels have been added to the pull request

### CODE REVIEW

**Comment by connersaeli** [comment]
@aaronweeden I have followed the exact steps (including the code change) and for this request:
```
https://localhost:8443/rest/v1.0/warehouse/search/jobs/analytics?realm=SUPREMM&recordid=0&jobid=1&infoid=7&token=b2740c570976e45fbf5239edea8f3881&_dc=1703190705018
```
I get this response (trimmed for readability)
```
{ 
  0 : {key : "CPU User Balance".....},	
  1 : {key: "Homogeneity"....},
  2 : {key: "Memory Headroom".....},
  3 : {key: Walltime Accuracy...},
  4 : {key: "CPU User"....}
}
```
I have tried clearing the cache, but I still don't get what I'd expected:
```
{ 
  0 : {key : "CPU User".....},	
  1 : {key: "Homogeneity"....},
  2 : {key: "CPU User Balance".....},
  3 : {key: "Memory Headroom"...},
  4 : {key: "Walltime Accuracy"....}
}
```
Is this the intended behavior?

**Comment by aaronweeden** [comment]
@connersaeli the ordering is done on the front end in JavaScript after that response is received to make sure the HTML shows the analytics in the expected order. I'm not aware of anything else depending on that order, so I didn't bother changing the response from the `rest/warehouse/search/jobs/analytics` endpoint.

**Comment by connersaeli** [comment]
So what you are saying is this change only affects the "traffic light" plots in the Job Viewer, correct?

**Comment by aaronweeden** [comment]
@connersaeli correct.

**Comment by connersaeli** [comment]
Ok I missed the comment in https://github.com/ubccr/xdmod-supremm/pull/256 that mentions that the order of the analysis fields in the REST response changed. I was confused why your change is necessary, but it makes sense now.

**Comment by connersaeli** [comment]
How did you check that your changes follow the new ordering?

**Comment by aaronweeden** [comment]
@connersaeli following the steps in the "Tests performed" in this PR's description, when the order is incorrect it looks like this:
Screenshot 2023-12-21 at 4 34 58 PM
When the order is correct it looks like this:
Screenshot 2023-12-21 at 4 36 44 PM

**Comment by connersaeli** [comment]
Ok thanks for the clarification. I can replicate that exactly.

**Review by connersaeli — APPROVED** [review]

**Pull request merged**
