### PR TITLE
Remove database guide

### PR DESCRIPTION
**Pull request by jtpalmer**
## Description

Removes the database guide.

## Motivation and Context

This was never really much of a guide and doesn't really serve any purpose.  It hasn't been maintained as databases have changed.  I think we should at least consider getting rid of it.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project as found in the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by plessbd** [comment]
so in the https://github.com/ubccr/hpc-toolset-tutorial we specifically mentioned that it was "possible" 

```
#------------------------                                                                                                      # Open XDMoD setup is designed to configure a local MySQL/MariaDB instance.                                                    # In this tutorial we use a seperate database. `xdmod-setup` can still be used to create the database tables on a remote database.                                                                                                                            # It is however necessary to manually create the user account and database schemas.                                            # The instructions to create the database user account and schemas are located: https://github.com/ubccr/hpc-toolset-tutorial/blob/master/database/create-xdmod-db.sh
```
not sure how well that translates to our official documentation though....

**Comment by jtpalmer** [comment]
@plessbd All things are possible.  We don't support it.  I'll put in a pull request to the tutorial to remove that sentence.

**Comment by jtpalmer** [comment]
@plessbd I can't find that paragraph in https://github.com/ubccr/hpc-toolset-tutorial , was it in the slides somewhere?

**Comment by plessbd** [comment]
It is part of the ASCIICinema.  @jpwhite4 and I specifically added it because the demo docker is setup with mariadb on a separate host and was specifically added because of the difference with how the demo is setup and what our documentation says.

**Comment by jtpalmer** [comment]
@plessbd Which of the ASCIICinema videos is it in?

**Comment by plessbd** [comment]
https://asciinema.org/a/349237 and https://asciinema.org/a/349241

**Pull request merged**
