### PR TITLE
Add staging_resource_specifications table to cloud manage tables action

### PR DESCRIPTION
**Pull request by eiffel777**
Add the new staging_resource_specifications table to etl action that manages the cloud tables.

## Tests performed
Tested in docker

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project as found in the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by jtpalmer** [comment]
How is it that the shippable tests didn't catch this?

**Comment by eiffel777** [comment]
@jtpalmer When you shred a cloud resource specs file it will create the create the table for you which the shippable tests do. That's why it didn't fail.

**Comment by jtpalmer** [comment]
@eiffel777 and we don't do that on the development server?

**Comment by eiffel777** [comment]
@jtpalmer I didn't have the dev server shredding cloud resource files everyday so when I made the change yesterday that added the staging_resource_specifications table when ingestion ran this morning that staging table was never made.

**Pull request merged**
