### PR TITLE
Minor fix to logrotate rule

### PR DESCRIPTION
**Pull request by treydock**
## Description

Fix logrotate rule to avoid errors when `/var/log/xdmod` has ownership `apache:xdmod`.

## Motivation and Context

```
error: skipping "/var/log/xdmod/dwi.log" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.
error: skipping "/var/log/xdmod/exceptions.log" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.
error: skipping "/var/log/xdmod/query.log" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.
```

## Tests performed

Add `su apache xdmod` to `/etc/logroate.d/xdmod.conf` and run logrotate

```
# logrotate --debug /etc/logrotate.d/xdmod 
reading config file /etc/logrotate.d/xdmod
Allocating hash table for state file, size 15360 B

Handling 1 logs

rotating pattern: /var/log/xdmod/*.log  weekly (4 rotations)
empty log files are rotated, old logs are removed
switching euid to 48 and egid to 80
considering log /var/log/xdmod/dwi.log
  log does not need rotating (log has been rotated at 2018-3-5 9:0, that is not week ago yet)
considering log /var/log/xdmod/exceptions.log
  log does not need rotating (log has been rotated at 2018-3-5 9:0, that is not week ago yet)
considering log /var/log/xdmod/query.log
  log does not need rotating (log has been rotated at 2018-3-5 9:0, that is not week ago yet)
considering log /var/log/xdmod/session_manager.log
  log does not need rotating (log has been already rotated)considering log /var/log/xdmod/simplesamlphp.log
  log does not need rotating (log has been already rotated)switching euid to 0 and egid to 0
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project as found in the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by jtpalmer** [comment]
@treydock I tried using this change but it causes different errors since we also have other files in the same directory that are owned by root (`apache-access.log` and `apache-error.log`).  We also have a file that has both user and group of apache (`session_manager.log`).  I think we may need to add a separate section for each of those possible user/group ownership.

Thanks for bringing the issue to our attention.  I never thought to check if the log rotation was actually working or not.

**Comment by treydock** [comment]
@jtpalmer I didn't run into the Apache issue because I write all my apache logs to `/var/www/httpd` so that they can be ingested more easily with Splunk. Explicitly listing our the files may be only way to ensure `apache` owned vs `root` owned vs potentially `xdmod` owned files are handled correctly.

```
[root@xdmod xdmod]# ls -la /var/log/xdmod/
total 892
drwxrwxr-x   2 apache xdmod    4096 Mar 11 03:28 .
drwxr-xr-x. 15 root   root     4096 Mar 15 03:23 ..
-rw-------   1 apache xdmod       0 Mar 11 03:28 dwi.log
-rw-r--r--   1 root   root     6556 Mar  5 11:48 dwi.log-20180311
-rw-rw-r--   1 apache xdmod    7617 Mar 12 15:44 exceptions.log
-rw-rw-r--   1 apache xdmod    1444 Mar  9 16:39 exceptions.log-20180311.gz
-rw-rw-r--   1 apache xdmod       0 Mar 11 03:28 query.log
-rw-rw-r--   1 apache xdmod      20 Mar  5 09:38 query.log-20180311.gz
-rw-------   1 apache xdmod   77755 Mar 14 13:15 session_manager.log
-rw-r--r--   1 apache apache  31543 Mar 10 15:04 session_manager.log-20180311
-rw-------   1 apache xdmod       0 Mar 11 03:28 simplesamlphp.log
-rw-r--r--   1 apache apache 756273 Mar  5 14:43 simplesamlphp.log-20180311
```

Also just as FYI it's easy to get notified about failed cron (logrotate) if root user mail goes somewhere.  We either set `/etc/aliases` and `newaliases` command to send root mail somewhere or we forward all mail to a central mail server and that system has `/etc/aliases` setup to forward root's mail.

**Comment by jtpalmer** [comment]
@treydock Did you change the `su` options?  I think it was better the other way.  Those files need to be writable by the `xdmod` user.  I'll create a new pull request to move the Apache logs to a different directory (`/var/log/httpd`) by default since they don't need to be in `/var/log/xdmod`.

**Comment by treydock** [comment]
I switched to just `apache` because I kept getting `Operation not permitted` when doing `xdmod` as the group, likely because the `apache` user is not a member of that group on my system.

```
/var/log/xdmod/*.log {
  compress
  create 0660 apache xdmod
  dateext
  missingok
  notifempty
  rotate 4
  weekly
  su apache xdmod
}
```

```
# logrotate -f -v /etc/logrotate.d/xdmod 
reading config file /etc/logrotate.d/xdmod
Allocating hash table for state file, size 15360 B

Handling 1 logs

rotating pattern: /var/log/xdmod/*.log  forced from command line (4 rotations)
empty log files are not rotated, old logs are removed
switching euid to 48 and egid to 80
considering log /var/log/xdmod/dwi.log
  log does not need rotating (log is empty)considering log /var/log/xdmod/exceptions.log
  log needs rotating
considering log /var/log/xdmod/query.log
  log does not need rotating (log is empty)considering log /var/log/xdmod/session_manager.log
  log needs rotating
considering log /var/log/xdmod/simplesamlphp.log
  log does not need rotating (log is empty)rotating log /var/log/xdmod/exceptions.log, log->rotateCount is 4
dateext suffix '-20180320'
glob pattern '-[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'
renaming /var/log/xdmod/exceptions.log to /var/log/xdmod/exceptions.log-20180320
creating new /var/log/xdmod/exceptions.log mode = 0660 uid = 48 gid = 80
compressing log with: /bin/gzip
error: error setting owner of /var/log/xdmod/exceptions.log-20180320.gz to uid 48 and gid 48: Operation not permitted
rotating log /var/log/xdmod/session_manager.log, log->rotateCount is 4
dateext suffix '-20180320'
glob pattern '-[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'
renaming /var/log/xdmod/session_manager.log to /var/log/xdmod/session_manager.log-20180320
creating new /var/log/xdmod/session_manager.log mode = 0660 uid = 48 gid = 80
compressing log with: /bin/gzip
error: error setting owner of /var/log/xdmod/session_manager.log-20180320.gz to uid 48 and gid 48: Operation not permitted
switching euid to 0 and egid to 0

```

**Comment by treydock** [comment]
Tried a few more permutations.  Using `apache:xdmod` for `su` and `create` works on fresh install except for `session_manager.log` because it's owned `apache:apache`.  I went as far as putting `xdmod` user in `apache` group and `apache` user in `xdmod` group, still get `Operation not permitted`.

**Pull request merged**
