### PR TITLE
Remove unused parameters to Timeseries and Aggregate query classes

### PR DESCRIPTION
**Pull request by smgallo**
**See also ubccr/xdmod-xsede#144 and ubccr/xdmod-supremm#175**

## Description

Aggregate and Timeseries query classes are typically instantiated as shown below however, the last 3 parameters are not used. Clean up and remove these parameters from the code to simplify upcoming refactoring.
- `$query_groupname = 'query_groupname'`
- `array $parameterDescriptions = array()`
- `$single_stat = false`

```
$agg_query = new $query_classname(
    $this->_query->getAggregationUnit()->getUnitName(),
    $this->_query->getStartDate(),
    $this->_query->getEndDate(),
    null,
    null,
    array(),
    'tg_usage',
    array(),
    false
);
```
becomes
```
$agg_query = new $query_classname(
    $this->_query->getAggregationUnit()->getUnitName(),
    $this->_query->getStartDate(),
    $this->_query->getEndDate(),
    null,
    null,
    array()
);
```

### Files Modified

Remove `query_groupname` and `query_group_name` from:
- DataWarehouse/Query/Query.php
- User/Elements/QueryDescripter.php
- DataWarehouse/Access/MetricExplorer.php (`checkDataAccess` argument)
- html/controllers/metric_explorer/get_rawdata.php (`checkDataAccess` argument)
- tests/component/lib/AclsTest.php (`checkDataAccess` argument)
- html/controllers/metric_explorer/get_dw_descripter.php (unused variable)
- DataWarehouse/Query/Cloud/Aggregate.php
- DataWarehouse/Query/Jobs/Aggregate.php
- DataWarehouse/Query/Jobs/RawData.php
- DataWarehouse/Query/Storage/Aggregate.php
- DataWarehouse/Query/Timeseries.php 
- DataWarehouse/Query/Cloud/Timeseries.php
- DataWarehouse/Query/Jobs/Timeseries.php
- XSEDE/DataWarehouse/Query/Accounts/Aggregate.php
- XSEDE/DataWarehouse/Query/Allocations/Aggregate.php
- XSEDE/DataWarehouse/Query/Requests/Aggregate.php
- XSEDE/DataWarehouse/Query/ResourceAllocations/Aggregate.php
- XSEDE/DataWarehouse/Query/Accounts/Timeseries.php
- XSEDE/DataWarehouse/Query/Allocations/Timeseries.php
- XSEDE/DataWarehouse/Query/Requests/Timeseries.php
- XSEDE/DataWarehouse/Query/ResourceAllocations/Timeseries.php
- SUPREMM/DataWarehouse/Query/SUPREMM/Aggregate.php
- SUPREMM/DataWarehouse/Query/SUPREMM/RawData.php
- SUPREMM/DataWarehouse/Query/SUPREMM/UnionQuery.php

Remove `parameter_descriptions` and `parameterDescriptions` from:
- DataWarehouse/Query/Query.php
- User/Elements/QueryDescripter.php (`getAggregate()`, `getTimeseries()`, `getAllQueries()`)
- DataWarehouse/Query/Cloud/Aggregate.php
- DataWarehouse/Query/Jobs/Aggregate.php
- DataWarehouse/Query/Jobs/RawData.php
- DataWarehouse/Query/Storage/Aggregate.php
- DataWarehouse/Query/Timeseries.php 
- DataWarehouse/Query/Cloud/Timeseries.php
- DataWarehouse/Query/Jobs/Timeseries.php
- XSEDE/DataWarehouse/Query/Accounts/Aggregate.php
- XSEDE/DataWarehouse/Query/Allocations/Aggregate.php
- XSEDE/DataWarehouse/Query/Requests/Aggregate.php
- XSEDE/DataWarehouse/Query/ResourceAllocations/Aggregate.php
- XSEDE/DataWarehouse/Query/Accounts/Timeseries.php
- XSEDE/DataWarehouse/Query/Allocations/Timeseries.php
- XSEDE/DataWarehouse/Query/Requests/Timeseries.php
- XSEDE/DataWarehouse/Query/ResourceAllocations/Timeseries.php
- SUPREMM/DataWarehouse/Query/SUPREMM/Aggregate.php
- SUPREMM/DataWarehouse/Query/SUPREMM/RawData.php
- SUPREMM/DataWarehouse/Query/SUPREMM/UnionQuery.php

Remove `single_stat` from:
- DataWarehouse/Query/Query.php
- User/Elements/QueryDescripter.php (`getAggregate()`, `getTimeseries()`, `getAllQueries()`)
- DataWarehouse/Query/Cloud/Aggregate.php
- DataWarehouse/Query/Jobs/Aggregate.php
- DataWarehouse/Query/Jobs/RawData.php
- DataWarehouse/Query/Storage/Aggregate.php
- DataWarehouse/Query/Timeseries.php 
- DataWarehouse/Query/Cloud/Timeseries.php
- DataWarehouse/Query/Jobs/Timeseries.php
- XSEDE/DataWarehouse/Query/Accounts/Aggregate.php
- XSEDE/DataWarehouse/Query/Allocations/Aggregate.php
- XSEDE/DataWarehouse/Query/Requests/Aggregate.php
- XSEDE/DataWarehouse/Query/ResourceAllocations/Aggregate.php
- XSEDE/DataWarehouse/Query/Accounts/Timeseries.php
- XSEDE/DataWarehouse/Query/Allocations/Timeseries.php
- XSEDE/DataWarehouse/Query/Requests/Timeseries.php
- XSEDE/DataWarehouse/Query/ResourceAllocations/Timeseries.php
- SUPREMM/DataWarehouse/Query/SUPREMM/Aggregate.php
- SUPREMM/DataWarehouse/Query/SUPREMM/RawData.php
- SUPREMM/DataWarehouse/Query/SUPREMM/UnionQuery.php

Remove `getQueryGroupname()` and `setQueryGroupname()` from:
- DataWarehouse/Query/Query.php

Remove parameters from Query constructor calls in:
- User/Elements/QueryDescripter.php

Remove parameters from `Aggregate` and `Timeseries` instantiations:
- DataWarehouse/Access/MetricExplorer.php
- DataWarehouse/Data/SimpleTimeseriesDataset.php
- DataWarehouse/Visualization/HighChartTimeseries2.php
- DB/FilterListBuilder.php
- DataWarehouse/Data/ComplexDataset.php
- DataWarehouse/Data/SimpleTimeseriesDataset.php
- Rest/Controllers/WarehouseControllerProvider.php
- html/controllers/metric_explorer/get_rawdata.php

Remove "tg_usage" string from
- Models/Services/Acls.php (`new QueryDescriptor`)
- DataWarehouse/Access/MetricExplorer.php (`getRealmsFromUser` unused parameter)
- html/controllers/metric_explorer/get_dw_descripter.php
- html/controllers/ui_data/summary3.php
- tests/component/lib/AclsTest.php

Remove unused class DataWarehouse/Query/Jobs/Raw.php
## Motivation and Context

Code cleanup in preparation for refactoring.

## Tests performed

Ran existing tests

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project as found in the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by jpwhite4** [comment]
Any idea what the UnionQuery class is?

**Comment by jpwhite4** [comment]
Looks like UnionQuery was some test code that should never have been added to the repo.

T'was added in this commit:
commit 578ef4a65edacbacf5398ff4c27407ad09dda8e3
Date:   Tue Jun 23 11:28:47 2015 -0400

Then made obsolete ~3.5 hours later in this commit:
commit 85d6e37218e34fccb6229f3239b1d19fc2f8c3a9
Date:   Tue Jun 23 15:04:04 2015 -0400

**Comment by smgallo** [comment]
@jpwhite4 UnionQuery has now been removed from the SUPReMM code in ubccr/xdmod-supremm#175

**Comment by smgallo** [comment]
@jpwhite4 @plessbd 	@ryanrath Latest updates to configuration cache invalidation allow SUPReMM tests to pass. Please review ubccr/xdmod-xsede#144 and ubccr/xdmod-supremm#175

**Pull request merged**
